### PR TITLE
Opt to use OpenGL 2.0 instead of software rendered OpenGL 4.1

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR checks if the best detected OpenGL version isn't using software rendering provided by the OS instead of a GPU renderer. With newer versions of Qt on OSX (and Linuxes ?), requesting a 4.1 context on a GPU that does not support hardware accelerated 4.1 rendering results in a software rendered context which is much slower than a hardware accelerated 2.0 context. This PR detects software rendering OpenGL 4.1 renderers, and falls back to OpenGL 2.0 instead. 

Contributes to https://github.com/Ultimaker/Cura/issues/4505 (CURA-6092)

This will need testing on many systems.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I had a choice to "contaminate" QtApplication with some OpenGL, or "contaminate" OpenGLContext with some Qt. I chose the former.

**Comment by nallath** [comment]
You're hive mind is strong here. I was just typing a message as to why you chose to do it like this.

**Comment by nallath** [comment]
Shit. It seems that this isn't a solution we can take :( 

The line `gl = QOpenGLContext.currentContext().versionFunctions()` is causing a crash for me (`ModuleNotFoundError: No module named 'PyQt5._QOpenGLFunctions_4_5_Core'`). I really hope this is just an issue with my setup...

**Comment by nallath** [comment]
I have found a way to keep it in the 'detectBestOpenGLVersion' though, but I can't actually run it due to the crash :(

**Comment by fieldOfView** [comment]
I am now using QOpenGLContext.currentContext().versionFunctions() the same way OpenGL.py does it. Could you try again?

**Comment by nallath** [comment]
Nope, still nothing :( ModuleNotFoundError: No module named 'PyQt5._QOpenGLFunctions_4_5_Core'

I've also tried to use ctx.versionFunctions() and ctx.versionFunctions(gl_profile) , but neither work.

**Comment by nallath** [comment]
What version of PyQt are you using? I'm getting the feeling it has to do with that.

**Comment by fieldOfView** [comment]
I'm using 5.10.

**Comment by nallath** [comment]
Hmm. That must be it then, I'm on 5.11.3

**Comment by fieldOfView** [comment]
Cura uses 5.10 though, right?

**Comment by nallath** [comment]
Yeah, it does. But this was the only version I could get to run with qml debugging. I could downgrade back again, but that's just going to postpone the problem until we do...

**Comment by fieldOfView** [comment]
But at least it would tell us if it is indeed the PyQt version.

Note that I don't understand how it fails. OpenGL.py does exactly the same here: https://github.com/Ultimaker/Uranium/blob/master/UM/View/GL/OpenGL.py#L54

**Comment by nallath** [comment]
Yeah, I'm also at a loss here. I guess it has something to do with the moment when it happens. The openGL object is created on the first render call from the window (as the first time render is called, it creates a qtRenderer, which in turn creates that object).

**Comment by fieldOfView** [comment]
In that case, could you try changing gl_widget.showMinimized() to gl_widget.show(), because then the window actually gets painted.

**Comment by nallath** [comment]
Tried that one already, it didn't matter. I still get the same result

**Comment by nallath** [comment]
Using PyOpenGL does seem to do the trick though. But that would mean that we'd have to add an extra dependency for just this....

**Comment by fieldOfView** [comment]
I think I found the issue:
https://riverbankcomputing.com/pipermail/pyqt/2017-January/038640.html

> PyQt currently only implements 2.0, 2.1 and 4.1Core

Looks like the detection finds the possibility to use 4.5Core on your system, but then PyQt cannot handle that context/version when we try to create it.

I've changed the code to always create the test-context with 4.1 even if something >4.1 is detected.

**Comment by nallath** [comment]
That did the trick, no more crashes.

**Comment by thopiekar** [comment]
And what happens if I run this in a virtual machine (KVM)? There I want software rendering if I have no 3D accelerator. Or is Qt providing its own renderer?

**Comment by fieldOfView** [comment]
The PR only rejects software 4.1 contexts. The application then continues to check if a 2.1 context is available. There is no check if the 2.1 context uses software rendering. So in your VM scenario, you end up with a software rendered gl context. In my testing, a software rendered 2.1 context performs better than a software 4.1 context (especially in Layer View, where the geometry shader does not have to draw in software mode).

**Comment by thopiekar** [comment]
Great! Thank you for your feedback! 😃

**Comment by fieldOfView** [comment]
I will see if I can create a 4.0 build with a backport of this fix this weekend, for affected OSX users to test (and use).

**Comment by fieldOfView** [comment]
Looks like this needs a bit more work when running "frozen" on OSX.

**Comment by LipuFei** [comment]
@fieldOfView I've created a branch from yours and I will create Cura builds with it. Branch: https://github.com/Ultimaker/Uranium/tree/CURA-6092_aldo_opengl_fix_mac

**Comment by LipuFei** [comment]
@fieldOfView I got a crash on my Mac (Mojave 10.14.3) :(
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/env/master/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/env/master/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/ultimaker/build/master/build/inst/bin/cura_app.py", line 136, in <module>
  File "/Users/ultimaker/build/master/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 716, in run
  File "/Users/ultimaker/build/master/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 291, in run
  File "/Users/ultimaker/build/master/build/inst/lib/python3.5/site-packages/UM/Application.py", line 209, in run
  File "/Users/ultimaker/build/master/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 316, in initialize
  File "/Users/ultimaker/build/master/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 131, in initialize
  File "/Users/ultimaker/build/master/build/inst/lib/python3.5/site-packages/UM/View/GL/OpenGLContext.py", line 135, in detectBestOpenGLVersion
AttributeError: 'NoneType' object has no attribute 'initializeOpenGLFunctions'

```

**Comment by nallath** [comment]
I do have an idea for a band-aid solution to the issue; We can also add a message that if the 4.1 context is selected with a software renderer, it warns the user that this is the case and provides a button / action to force the compatibility mode.

It isn't as elegant as the automatic solution, but it's pretty much guaranteed to work (since it's just adding a message and doesn't need any "fundamental" changes to our detection)

**Comment by fieldOfView** [comment]
@LipuFei, that's what I meant with that it needs some work. Apparently opening the hidden window does not let Qt initialise OpenGL on OSX (it does on Windows).

What GPU does your Mac have? Does it normally have hardware accelerated OpenGL 4.1?

**Comment by nallath** [comment]
We only have macs that have a hardware accelerated 4.1 OpenGL (which is why we didnt find the issue in the first place).

**Comment by fieldOfView** [comment]
I have found a better way to initialize OpenGL to get the renderer, which also works on OSX. 

This PR works properly on my OS X VM, which now correctly creates a (software) 2.0 context instead of a software 4.1 context. Would be nice to know if it still creates a 4.1 context on real hardware that supports it.

**Comment by LipuFei** [comment]
@fieldOfView 👍 This works on my Mac (Mojave 10.14.4).

**Comment by fieldOfView** [comment]
🍾

Reports here are also favorable for macs that are affected by the issue (with 4.1-challenged gpus)
https://github.com/Ultimaker/Cura/issues/4505#issuecomment-482462148

I have not tested this latest iteration on Linux yet.

**Comment by diegopradogesto** [comment]
I checked on macOS as well and it seems to work fine. @nallath checked on Linux and said it was OK.

Thanks for contributing on fixing this issue.
